### ISSUE TITLE
GraphToRules prefix issue

### ISSUE THREAD

**Issue by msolvik** [cognitedata/neat#148]
**Describe the bug**
When creating a data model based on an rdf Graph (using GraphToRules from standard lib), an issue is detected when having 2 prefixes with similar start. 

Example 
prefix-1: https://test.no/schema/common/
prefix-2: https://test.no/schema/common/enrichment/

In the generated excel sheet, prefix-2 is not entered, but "prefix-1:enrichment/". This leads to error when trying to load the generated transformation rule sheet. 

**Expected behavior**
"prefix-2:" is expected instead of "prefix-1:enrichment/"

**Comment by nikokaoja** [comment]
This has been solved in one of the previous PRs (DEXPI extractor)
@msolvik , I will close this issue, give
