### ISSUE TITLE
GraphToRules: Converting "." in property name to "_" 

### ISSUE THREAD

**Issue by msolvik** [cognitedata/neat#150]
**Is your feature request related to a problem? Please describe.**

GraphToRules generates property names such as "Fragment.id", which is not allowed in CDF. 

**Describe the solution you'd like**
the property name should be converted to a CDF valid name, such as "Fragment_id", together with a warning about the changes.

**Comment by alivinco** [comment]
Possibly should be done similarly to ArbitraryJsonYamlToRules step , where the conversion (set of conversion rules ) is controlled by setting `fdm_compatibility_mode` configuration parameter 
![React_App](https://github.com/cognitedata/neat/assets/1312867/3bdbfa4c-9c59-4806-9972-0d35a71806df)
