### ISSUE TITLE
Request: Description Length Limit Increase for DMS Importer

### ISSUE THREAD

**Issue by redzarosliCognite** [cognitedata/neat#164]
Hey, question about DMSImporter. When the data importer pulls a view from FDM, the importer imposes a limit on the length of the description (at most 255 characters ). It triggers this error when a property description is too long. Please could we increase this limitation.

```
ValidationError: 1 validation error for Rules
properties.row 10.Description
  String should have at most 255 characters [type=string_too_long, input_value='When Furnished Enter The...i\n@name: TRIM MATERIAL', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/string_too_long
```

**Comment by nikokaoja** [comment]
This is solved now :)
