### ISSUE TITLE
Handle no model available when calling DMSImporter.from_cdf 

### ISSUE THREAD

**Issue by spex66** [cognitedata/neat#194]
**Is your feature request related to a problem? Please describe.**
Running `my_model = DMSImporter.from_cdf(client, [('dp-osdu-spc', 'my-model')])` where space or model does not exists results in NEAT throwing a traceback, as it expects a data-model being available

```py
File ~/../python3.10/site-packages/cognite/client/data_classes/_base.py:233, in CogniteResourceList.__getitem__(self, item)
    230 def __getitem__(
    231     self: T_CogniteResourceList, item: SupportsIndex | slice
    232 ) -> T_CogniteResource | T_CogniteResourceList:
--> 233     value = self.data[item]
    234     if isinstance(item, slice):
    235         return type(self)(value, cognite_client=self._get_cognite_client())

IndexError: list index out of range
```

**Describe the solution you'd like**
NEAT can add handling missing data-model and respond with smth like "no model available to import" instead of throwing an error.

**Describe alternatives you've considered**
Checked if it is the default behavior of Python SDK (v6 and v7), and can confirm that `.retrieve(..)` method for classic and new data-model resources is not throwing an error on missing/wrong identifier.

**Additional context**
Discussed on Slack today

**Comment by nikokaoja** [comment]
This is part of legacy code base which is not maintained anymore. 
New version must be used to have latest features and robust package.
