### ISSUE TITLE
DMSImporter.from_cdf does not retrieve latest version, if no version is given

### ISSUE THREAD

**Issue by spex66** [cognitedata/neat#195]
**System information (please complete the following information):**
 - Python Version: 3.10
 - neat Version: 0.41.6

**Describe the bug**
Requesting `importer.DMSImporter.from_cdf(client, [('my-spc', 'my_model')])` w/o an explicit  version given, is supposed to respond with *latest version*.

Multiple issues I see here:
1. SDK request `my_models  = client.data_modeling.data_models.retrieve(('my-spc', 'my_model')` responds with versions sorted alphabetically.
  - in my case the list of versions looks like
```py
[v.version for v in my_models]
#> ['1', '10', '11', '2', '3', '4', '5', '6', '7', '8', '9']
```
2. NEAT implemented access on top of this request `[0]` (in `DMSImporter.from_cdf`) which responds with **1** instead of **11**
3. `version` is defined as `^[a-zA-Z0-9]([.a-zA-Z0-9_-]{0,41}[a-zA-Z0-9])?$`, not only integers
 - I'm not sure how to retrieve **latest**, sounds like a SDK or API question
 - maybe sorting by `created_time` and picking last is it?
```py
[v.version for v in sorted(copilot_cdf_model, key=lambda x: x.created_time)]
#> ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']
```

**To Reproduce**
You need models with multiple versions
- like including 1, 2 and 10

**Expected behavior**
Retrieve model with **latest** version

**Screenshots**

**Additional context**

**Comment by nikokaoja** [comment]
This in legacy module, and we do not intend to spend resources improving legacy code.
