### ISSUE TITLE
DMSImporter.to_tables() should handle views with no properties

### ISSUE THREAD

**Issue by spex66** [cognitedata/neat#196]
**Is your feature request related to a problem? Please describe.**
`DMSImporter.to_rules(..)` is calling `to_tables()`, which fails if a view has no properties
```py
File ~/git/cog/neat/cognite/neat/rules/importer/_dms2rules.py:97, in DMSImporter.to_tables(self)
     95 class_id = view.external_id
     96 classes.append({"Class": class_id, "Description": view.description or float("nan")})
---> 97 for prop_id, prop in view.properties.items():
     98     if isinstance(prop, MappedProperty):
     99         # Edge 1-1
    100         if isinstance(prop.type, DirectRelation):

AttributeError: 'NoneType' object has no attribute 'items'
```

**Describe the solution you'd like**
Check if a view has no properties, and dependent if this is supported in NEAT 
- fail with a helpful error message
- or handle views w/o properties

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nikokaoja** [comment]
@spex66 , I do not think you can create `View` without any properties, so I am closing this down
