### ISSUE TITLE
Documentation improvement, reuse `neat.utils.utils import get_cognite_client_from_config`

### ISSUE THREAD

**Issue by spex66** [cognitedata/neat#198]
**Is your feature request related to a problem? Please describe.**
Chapter [ Part 5 Load Graph to FDM Containers](https://cognite-neat.readthedocs-hosted.com/en/latest/tutorial/notebooks/part-5-knowledge-graph-to-fdm-instances.html) is creating a CogniteClient too complicated 

**Describe the solution you'd like**

You have already introduced a NEAT helper method, which you should use everytime
```py
from cognite.neat.app.api.configuration import Config
from cognite.neat.utils.utils import get_cognite_client_from_config
cfg = Config().from_yaml(Path('../config.yaml'))

client = get_cognite_client_from_config(cfg.cdf_client)
```

Reducing the import path from `utils.utils` to `utils` is a plus, just provide it from `__init__.py` from parent `utils` :)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nikokaoja** [comment]
We have removed all the old notebooks, this issue is moved to JIRA
