### ISSUE TITLE
Change Default Label 'non-historic' in AssetLoader

### ISSUE THREAD

**Issue by doctrino** [cognitedata/neat#242]
Since none-historic / historic label is a very specific to a paricular customer, would it be more "generic" if we use for example of the following pairs:
Active - Inactive
Operational - Non-operational
Live - Dormant
Functioning - Deactivated
Online - Offline
Working - Idle
Engaged - Disengaged
Enabled - Disabled
Ongoing - Stopped
Operational - Inert
...

_Originally posted by @nikokaoja in https://github.com/cognitedata/neat/pull/241#discussion_r1461787015_

**Comment by nikokaoja** [comment]
This is fixed
